name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Checkout gh-pages Branch
        run: git checkout gh-pages

      - name: Copy Build Artifacts
        run: cp -r build/* .

      - name: Commit and Push to gh-pages Branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@example.com"
          git add .
          git commit -m "Build and deploy to GitHub Pages"
          git push origin gh-pages --force
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          
